### ISSUE TITLE
Not a valid key: dump-structure

### ISSUE THREAD

**Issue by thorie7912** [JetBrains/sbt-structure#38] opened 2016-05-05 00:26 UTC
IntelliJ 15.0.5 Build: IU-143.2332, built on March 23, 2016
JRE: 1.8.0_40-release-b132 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

Scala Plugin version 2.2.0

Getting this error, no idea how to fix it:

```
...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn]  * com.typesafe.sbt:sbt-native-packager:0.7.4 -> 0.8.0
[warn] Run 'evicted' to see detailed eviction warnings
[info] Set current project to root
> [info] Defining root/*:shellPrompt
[info] The new value will be used by no settings or tasks.
[info] Reapplying settings...
[info] Set current project to root
<set>:1: error: type mismatch;
 found   : sbt.File
    (which expands to)  java.io.File
 required: File
SettingKey[Option[File]]("sbt-structure-output-file") in Global := Some(file("/private/var/folders/dy/rgyl8_8n1dqf5zgn3x4w62t1qv1ztd/T/sbt-structure0.xml"))
                                                                            ^
[error] Type error in expression
[info] Defining */*:sbtStructureOptions
[info] The new value will be used by no settings or tasks.
[info] Reapplying settings...
[info] Set current project to root 
[info] Applying State transformations org.jetbrains.sbt.CreateTasks from ~/Library/Application Support/IntelliJIdea15/Scala/launcher/sbt-structure-0.13.jar
Reference to undefined setting: 

  */*:sbtStructureOutputFile from */*:dumpStructure ((org.jetbrains.sbt.CreateTasks) CreateTasks.scala:15)

    at sbt.Init$class.Uninitialized(Settings.scala:265)
    at sbt.Def$.Uninitialized(Def.scala:10)
    at sbt.Init$class.delegate(Settings.scala:191)
    at sbt.Def$.delegate(Def.scala:10)
    at sbt.Init$class.compiled(Settings.scala:138)
    at sbt.Def$.compiled(Def.scala:10)
    at sbt.Init$class.make(Settings.scala:144)
    at sbt.Def$.make(Def.scala:10)
    at sbt.Project$.makeSettings(Project.scala:350)
    at sbt.Load$.reapply(Load.scala:187)
    at org.jetbrains.sbt.CreateTasks$.applySettings(CreateTasks.scala:60)
    at org.jetbrains.sbt.CreateTasks$.apply(CreateTasks.scala:50)
    at org.jetbrains.sbt.CreateTasks$.apply(CreateTasks.scala:10)
    at sbt.BasicCommands$$anonfun$call$2$$anonfun$apply$9.apply(BasicCommands.scala:121)
    at sbt.BasicCommands$$anonfun$call$2$$anonfun$apply$9.apply(BasicCommands.scala:121)
    at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:111)
    at scala.collection.immutable.List.foldLeft(List.scala:84)
    at scala.collection.TraversableOnce$class.$div$colon(TraversableOnce.scala:138)
    at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:105)
    at sbt.BasicCommands$$anonfun$call$2.apply(BasicCommands.scala:121)
    at sbt.BasicCommands$$anonfun$call$2.apply(BasicCommands.scala:115)
    at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
    at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
    at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
    at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
    at sbt.Command$.process(Command.scala:92)
    at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
    at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
    at sbt.State$$anon$1.process(State.scala:184)
    at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
    at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.MainLoop$.next(MainLoop.scala:98)
    at sbt.MainLoop$.run(MainLoop.scala:91)
    at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
    at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
    at sbt.Using.apply(Using.scala:24)
    at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
    at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
    at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
    at sbt.MainLoop$.runLogged(MainLoop.scala:24)
    at sbt.StandardMain$.runManaged(Main.scala:53)
    at sbt.xMain.run(Main.scala:28)
    at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
    at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
    at xsbt.boot.Launch$.run(Launch.scala:109)
    at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
    at xsbt.boot.Launch$.launch(Launch.scala:117)
    at xsbt.boot.Launch$.apply(Launch.scala:18)
    at xsbt.boot.Boot$.runImpl(Boot.scala:41)
    at xsbt.boot.Boot$.main(Boot.scala:17)
    at xsbt.boot.Boot.main(Boot.scala)
[error] Reference to undefined setting: 
[error] 
[error]   */*:sbtStructureOutputFile from */*:dumpStructure ((org.jetbrains.sbt.CreateTasks) CreateTasks.scala:15)
[error]  
[error] Use 'last' for the full log.
[error] Not a valid key: dump-structure (similar: build-structure, buildStructure)
[error] */*:dump-structure
[error]                   ^
```

Deleting the .idea folder and re-importing the project doesn't seem to make any difference.
What does this error mean?

**Comment by scalamorphing** [comment] 2016-06-26 07:49
This bug reproduces in my project.

**Comment by thorie7912** [comment] 2016-07-07 20:46
If anyone is stuck on this, the current workaround is to install IntelliJ 14 first, then add your project, then upgrade to a newer IntelliJ. It will migrate your project successfully.

**Comment by leoromanovsky** [comment] 2016-07-13 22:27
Thanks for the note @thorie7912 - I couldn't get your instructions to work. Could you elaborate more about how you got it working?

**Comment by thorie7912** [comment] 2016-07-13 22:30
@leoromanovsky Basically, you want to install an older version of IntelliJ and open your project from it. In my case, the project was originally created in IntelliJ 14 but it wasn't loading in IntelliJ 15. So I re-installed IntelliJ 14, and added my project. That gave me no errors. Then, when I upgraded to IntelliJ 15, it also migrated the project without any issues. Does that make sense? I don't know if this will work for everyone, but it worked for me.

**Comment by jastice** [comment] 2016-08-10 13:08
Interesting, we've never come across this. Is there a reliable way to reproduce?

**Comment by thorie7912** [comment] 2016-08-10 21:23
It's very reproducible with my project files. If I can narrow it down to a dummy set of files instead of my real project, I'll post it here.

**Comment by jastice** [comment] 2016-08-10 21:35
Thanks! If you could post it to [YouTrack](https://youtrack.jetbrains.com/issues/SCL), that would be helpful for tracking the fix.

**Comment by leoromanovsky** [comment] 2016-08-10 21:55
I was able to resolve this issue on my end by correcting the following in my `Build.scala` file:

`lazy val sbt = Project(..)`

to 

`lazy val anythingButSbt = Project(...)`

**Comment by thorie7912** [comment] 2016-08-10 23:16
I don't have a `Build.scala` file. But I do have a `build.sbt` file.

**Comment by thorie7912** [comment] 2016-10-29 04:12
I think I finally produced a minimal project that exhibits this error. It still happens in IntelliJ 2016.2.5

https://github.com/thorie7912/dump-structure

@jastice Does this help?

**Comment by jastice** [comment] 2016-10-30 12:16
Thanks! The issue is that CheckstyleSettings.scala defines a case class `File`, which shadows `sbt.File`, which is used by the import process. If you rename it the import works.

I'm pushing a fix that uses fully qualified paths so that this doesn't happen in future versions :)

**Comment by leoromanovsky** [comment] 2016-10-30 17:08
@jastice - do you have a commit or PR you can please tag to this ticket?

**Comment by jastice** [comment] 2016-10-30 17:23
Here it is: https://github.com/JetBrains/intellij-scala/commit/bb0930e78628594de777d285c19e677eb40dd678

**Comment by btomala** [comment] 2016-11-22 11:00
Hey, I got similar issue but looks like introduced by above bug fix. Yesterday I install new IntellIJ. And when I load the project I got such error:

> [success] Total time: 0 s, completed 22-Nov-2016 11:19:15
> <set>:1: error: value lang is not a member of sbt.TaskKey[java.io.File]
> SettingKey[java.lang.String]("sbt-structure-options") in Global := "download, resolveClassifiers"
>                 ^
> [error] Type error in expression
> [info] Applying State transformations org.jetbrains.sbt.CreateTasks from /home/bartek/.IntelliJIdea2016.3/config/plugins/Scala/launcher/sbt-structure-0.13.jar
> [info] Reapplying settings...
> Reference to undefined setting: 
> 
>   */*:sbtStructureOptions from */*:ssOptions ((org.jetbrains.sbt.CreateTasks) CreateTasks.scala:13)
>  
> 	at sbt.Init$class.Uninitialized(Settings.scala:270)
> 	at sbt.Def$.Uninitialized(Def.scala:10)
> 	at sbt.Init$class.delegate(Settings.scala:191)
> 	at sbt.Def$.delegate(Def.scala:10)
> 	at sbt.Init$class.compiled(Settings.scala:138)
> 	at sbt.Def$.compiled(Def.scala:10)
> 	at sbt.Init$class.make(Settings.scala:144)
> 	at sbt.Def$.make(Def.scala:10)
> 	at sbt.Load$.reapply(Load.scala:197)
> 	at sbt.BuiltinCommands$.reapply(Main.scala:242)
> 	at sbt.SessionSettings$.reapply(SessionSettings.scala:92)
> 	at org.jetbrains.sbt.CreateTasks$.applySettings(CreateTasks.scala:60)
> 	at org.jetbrains.sbt.CreateTasks$.apply(CreateTasks.scala:50)
> 	at org.jetbrains.sbt.CreateTasks$.apply(CreateTasks.scala:10)
> 	at sbt.BasicCommands$$anonfun$call$2$$anonfun$apply$9.apply(BasicCommands.scala:131)
> 	at sbt.BasicCommands$$anonfun$call$2$$anonfun$apply$9.apply(BasicCommands.scala:131)
> 	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:111)
> 	at scala.collection.immutable.List.foldLeft(List.scala:84)
> 	at scala.collection.TraversableOnce$class.$div$colon(TraversableOnce.scala:138)
> 	at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:105)
> 	at sbt.BasicCommands$$anonfun$call$2.apply(BasicCommands.scala:131)
> 	at sbt.BasicCommands$$anonfun$call$2.apply(BasicCommands.scala:125)
> 	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
> 	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
> 	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
> 	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
> 	at sbt.Command$.process(Command.scala:93)
> 	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
> 	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
> 	at sbt.State$$anon$1.process(State.scala:184)
> 	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
> 	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
> 	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
> 	at sbt.MainLoop$.next(MainLoop.scala:96)
> 	at sbt.MainLoop$.run(MainLoop.scala:89)
> 	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)
> 	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
> 	at sbt.Using.apply(Using.scala:24)
> 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
> 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
> 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
> 	at sbt.MainLoop$.runLogged(MainLoop.scala:22)
> 	at sbt.StandardMain$.runManaged(Main.scala:54)
> 	at sbt.xMain.run(Main.scala:29)
> 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
> 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
> 	at xsbt.boot.Launch$.run(Launch.scala:109)
> 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
> 	at xsbt.boot.Launch$.launch(Launch.scala:117)
> 	at xsbt.boot.Launch$.apply(Launch.scala:18)
> 	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
> 	at xsbt.boot.Boot$.main(Boot.scala:17)
> 	at xsbt.boot.Boot.main(Boot.scala)
> [error] Reference to undefined setting: 
> [error] 
> [error]   */*:sbtStructureOptions from */*:ssOptions ((org.jetbrains.sbt.CreateTasks) CreateTasks.scala:13)
> [error]  
> [error] Use 'last' for the full log.
> [error] Not a valid key: dump-structure (similar: build-structure, buildStructure)
> [error] */*:dump-structure
> [error]                   ^

My IntelliJ is EAP.
> IntelliJ IDEA 2016.3
> Build #IU-163.7743.44, built on November 17, 2016
> Licensed to IntelliJ IDEA Evaluator
> Expiration date: December 21, 2016
> JRE: 1.8.0_112-b15 amd64
> JVM: OpenJDK 64-Bit Server VM by Oracle Corporation
>

**Comment by jastice** [comment] 2016-11-22 11:32
@btomala Could you provide a build definition/project in which this error reproduces for you? Thanks!

**Comment by btomala** [comment] 2016-11-22 12:46
@jastice It's not simple because we have internal plugin. I will try to prepare some base project to reproduce it for you. But I need some time.

**Comment by btomala** [comment] 2016-11-22 16:36
@jastice to reproduce bug you need to add 
`addSbtPlugin("com.typesafe.sbt" % "sbt-multi-jvm" % "0.3.11")` 
to `plugins.sbt` in @thorie7912 sample https://github.com/thorie7912/dump-structure

**Comment by zhaojin0** [comment] 2016-11-23 02:52
refresh failed, when "com.typesafe.sbt" % "sbt-multi-jvm" % "0.3.11"

safe at "com.typesafe.sbt" % "sbt-multi-jvm" % "0.3.9"

**Comment by mborra** [comment] 2016-11-23 08:53
With the new IntelliJ IDEA 2016.3 and "sbt-multi-jvm" % "0.3.11" I have the same issue

**Comment by jastice** [comment] 2016-11-23 10:38
Thanks all, I can fix the problem and it will be in the next bugfix update

**Comment by jastice** [comment] 2016-11-24 08:51
Youtrack issue: https://youtrack.jetbrains.com/issue/SCL-11005
closing this one

**Closed by jastice** 2016-11-24 08:51 UTC

**Comment by 4lex1v** [comment] 2017-01-13 18:23
Though the YoutTrack ticket marked as fixed, i'm still getting this issue trying to open [Quasar](https://github.com/quasar-analytics/quasar) project both in 2016.3.2 and 2017.1 EAP. As far as i can say MultiJVM plugin mentioned in this ticket, is not used by this project.

**Comment by jastice** [comment] 2017-01-13 18:49
Interesting, quasar uses the "-Yno-imports" flag, which ironically breaks the import. There's a fully qualified path I missed in my last fix. It will be in the next update.

**Comment by 4lex1v** [comment] 2017-01-13 18:56
@jastice indeed, removing the flag solves the issue, thanks

**Comment by ngbinh** [comment] 2017-02-10 17:06
I had the same problem with this plugin https://github.com/stonexx/sbt-webpack is there any work around for the issue?

**Comment by jastice** [comment] 2017-02-10 17:16
@ngbinh It should be working fine in the latest version of the Scala plugin. Which version are you on?

**Comment by ngbinh** [comment] 2017-02-11 05:30
I am using the latest version `2116.3.8`. It also happens to the EAP version

**Comment by jastice** [comment] 2017-02-11 10:39
Importing a project using the plugin works for me. Please provide an example project that reproduces the issue. Thanks!

**Comment by ngbinh** [comment] 2017-02-11 10:52
ok, will do
